# **SW01: Recap of NumPy arrays**

To fully appreciate how many machine learning algorithms work, a good understanding of linear algebra is required.  We cannot cover all the necessary concepts in this course, but we will outline some basic in this notebook. 

**Recommendation**: Take a look at the miniprimer on matrices and vectors in the course's git repository!


In [1]:
import numpy as np

---

## **Arrays and matrices**

In [2]:
########################
###    EXERCISE 1    ###
########################

# Create a NumPy array with values [2, 3, 4].
a = ...

a = np.array([2,3,4])
print(a)

[2 3 4]


In [3]:
########################
###    EXERCISE 2    ###
########################

# Initialize a NumPy array with a range [1, ..., 15] and reshape
# it into a matrix (2D-array) with 3 rows and 5 columns.
#  - Verify the shape of the resulting array. 
#  - What does the ndim attribute tell you?
a = ...

a = np.arange(1,16)
display(a)
display(a.reshape(3,5))
#with ndim you show the dimensions of the array
display(np.ndim(a))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

1


Let's operate from here on with the following two matrices:

$
A = \begin{pmatrix}1 & 1 & 2\\0 & 1 & 0\end{pmatrix}, \quad
B = \begin{pmatrix}2 & 0 & 1\\3 & 4 & 2\end{pmatrix}
$

We refer to the element in the $i$-th row and $j$-th column of the matrix as $a_{i,j}$ for the matrix $A$ and $b_{i,j}$ for the matrix $B$.



In [4]:
# Create the two matrices A and B.
A = np.array([[1, 1, 2],[0, 1, 0]])
B = np.array([[2, 0, 1],[3, 4, 2]])

display(A, B)

array([[1, 1, 2],
       [0, 1, 0]])

array([[2, 0, 1],
       [3, 4, 2]])

An elementary matrix operation is the transposition: $A^T$.
It is obtained by swapping the rows and columns of the matrix.

$A^T = \begin{pmatrix} 1 & 0 \\ 1 & 1 \\ 2 & 0 \end{pmatrix}$

In [5]:
# We can transpose a numpy array using the T attribute or 
# by using the function np.transpose().
A.T
np.transpose(A)

array([[1, 0],
       [1, 1],
       [2, 0]])

---

## **Matrix multiplication**

We can distinguish between two types of multiplication:
- Element-wise product: $c_{ij} = a_{ij} \cdot b_{ij}$
- Matrix multiplication (or dot product): $c_{ij} = \sum_k a_{ik} \cdot b_{kj}$

The element-wise multiplication is quite intuitive, while the matrix multiplication is a bit more complicated. (The miniprimer provides a good illustration of exactly how the calculation scheme works!)

For two NumPy arrays (of matching shape), we can compute the element-wise product using the **\* operator** (or `np.multiply()`), and the dot product using **@ operator** (or `np.dot()`):

```python
# Element-wise product
C = A*B
C = np.multiply(A,B)

# Dot product
C = A@B
C = np.dot(A,B)
```


In [6]:
########################
###    EXERCISE 3    ###
########################

# Compute the ELEMENT-WISE product of A and B by hand!
# What is the shape of the resulting matrix C?

#gleicher shape

In [7]:
########################
###    EXERCISE 4    ###
########################

# Compute the DOT product of A and B^T: A · B^T
# Can you give an answer why we need to transpose B?

In [8]:
########################
###    SOLUTION 4    ###
########################

# C = [[1*2 + 1*0 + 2*1, 1*3 + 1*4 + 2*2],
#      [0*2 + 1*0 + 0*1, 0*3 + 1*4 + 0*2]]
#   = [[4, 11],
#      [0, 4]]

# The calculation scheme for the dot product requires that the number of 
# columns in the first matrix (A) is equal to the number of rows in the 
# second matrix (B). Otherwise, the dot product is not defined.

In [9]:
# In Python, we can use the * operator (or np.multiply()) to compute the 
# element-wise product of NumPy arrays A and B.
A * B 
np.multiply(A, B)

array([[2, 0, 2],
       [0, 4, 0]])

In [10]:
# Similarly, we can use the @ operator (or np.dot()) to compute the dot product
# of NumPy arrays A and B.
A @ B.T
np.dot(A, B.T)

array([[ 4, 11],
       [ 0,  4]])

In [11]:
########################
###    EXERCISE 5    ###
########################

# Why does the following code snippet will give an error?

# Uncomment this line to see the error:
B @ A

#da die Dimension falsch ist

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [12]:
########################
###    EXERCISE 6    ###
########################

# Describe in words what each of the following expressions does:
print(B.sum(axis=0))
print(B.sum(axis=1))
print(B.sum())

# Can you think of other functions that can be used in a similar way?


[5 4 3]
[3 9]
12


---

## **Accessing array elements**

There are different ways to access of array elements: 

- Using indices or index arrays
- Using the slicing operator (`:`)
- Using boolean indexing (a.k.a. masking)

Let's recapitulate these methods using a new matrix C.

In [13]:
C = np.arange(1, 28).reshape(3, 9)
display(C)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [19]:
########################
###    EXERCISE 7    ###
########################

# a) Display the element at the second row and third column of matrix C.
# b) Display the first row of matrix C.
# c) Display the second column of matrix C.
# d) Display the submatrix of C that consists of the first two rows and columns.

In [37]:
#a 
display(C[1][3])

#b
display(C[0])

#c
display(C[:, 1])

#d
display(C[:-1,0:-7])

13

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 2, 11, 20])

array([[ 1,  2],
       [10, 11]])

In [24]:
########################
###    EXERCISE 8    ###
########################

# Explain what the following expressions do:
display(C[2])            # a) displays the third row
display(C[:, [1, 3]])    # b) displays the second and fourth number of each row and column
display(C[-1, :])        # c)displays the third row
display(C[:-1, 2:-3])    # d) displays the first and second row and the number from the second to the sixth position of these columns
display(C[:, 1:9:2])     # e) displays all three columns and every second number of each column from the second to the second last
display(C[:, ::-1])      # f) the matrix is mirror-inverted
display(C[::-1, ])       # g) the matrix is changed by one position of each row, so the thirst is now the last and so on...


array([19, 20, 21, 22, 23, 24, 25, 26, 27])

array([[ 2,  4],
       [11, 13],
       [20, 22]])

array([19, 20, 21, 22, 23, 24, 25, 26, 27])

array([[ 3,  4,  5,  6],
       [12, 13, 14, 15]])

array([[ 2,  4,  6,  8],
       [11, 13, 15, 17],
       [20, 22, 24, 26]])

array([[ 9,  8,  7,  6,  5,  4,  3,  2,  1],
       [18, 17, 16, 15, 14, 13, 12, 11, 10],
       [27, 26, 25, 24, 23, 22, 21, 20, 19]])

array([[19, 20, 21, 22, 23, 24, 25, 26, 27],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9]])

### Access submatrices using index arrays

In [38]:
i = [1, 1, 2, 5, 5, 5]  # an array of indices
display(C[:, i])

array([[ 2,  2,  3,  6,  6,  6],
       [11, 11, 12, 15, 15, 15],
       [20, 20, 21, 24, 24, 24]])

### Access submatrices using boolean indexing

In [39]:

# Pick all elements greater than 14.
mask = C > 14
display(mask)
display(C[mask])

# Pick all even elements.
# (Recall: % is the modulo operator)
mask = C % 2 == 0
display(C[mask])

# Pick all columns where all elements are divisible by 3.
mask = (C % 3 == 0).all(axis=0)
display(C[:, mask])

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26])

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [40]:
# New matrix
C = np.arange(1, 28).reshape(3, 9)
C


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

---

## **Functions and matrices**

Do you remember functions like $f(x) = x^3 + 9$ or $f(x) = \sin(x)$? 
Well, we can also apply these functions to NumPy arrays (and matrices). 
The corresponding functions are applied to the array element by element.


In [41]:
# Example 1
display(A**3 + 9)

# Example 2
display(np.sin(A))

array([[10, 10, 17],
       [ 9, 10,  9]])

array([[0.84147098, 0.84147098, 0.90929743],
       [0.        , 0.84147098, 0.        ]])